program: main.py
method: grid
metric:
  goal: minimize
  name: valid_MSE
early_terminate:
  min_iter: 10
  type: hyperband

parameters:
  # Dataset parameters
  dataset:
    value: V1_Breast_Cancer_Block_A
  cell_min_counts:
    value: 1000
  cell_max_counts:
    value: 100000
  gene_min_counts:
    value: 1000
  gene_max_counts:
    value: 1000000
  min_exp_frac:
    value: 0.8
  min_glob_exp_frac:
    value: 0.8
  top_moran_genes:
    value: 256
  wildcard_genes:
    value: None
  combat_key:
    value: slide_id
  random_samples:
    value: -1
  plotting_slides:
    value: V1_Breast_Cancer_Block_A_Section_1,V1_Breast_Cancer_Block_A_Section_2
  plotting_genes:
    value: ENSG00000115461,ENSG00000234745,ENSG00000143158,ENSG00000141232
  patch_scale:
    value: 1
  patch_size:
    value: 224
  force_compute:
    value: "false"
  prediction_layer:
    value: d_deltas
  n_hops:
    values: [1,2,3]

  # Model parameters
  sota:
    value: None
  img_backbone:
    value: ViT
  img_use_pretrained:
    value: "true"
  pretrained_ie_path:
    value: pretrained_ie_models/best_deltas_visium.pt
  freeze_img_encoder:
    value: "true"
  act:
    value: ELU
  graph_operator:
    values:
      - GCNConv
      - SAGEConv
      - GraphConv
      - GATConv
      - GATv2Conv
      - TransformerConv
  pos_emb_sum:
    values: ["true","false"]
  h_global:
    values:
      - //-1//0,256//-1
      - //-1//0,512,256//-1
      - //0,512,256//256,128,64//64,128,256
      - //-1//0,512,256,128//128,256
      - //-1//0,512,256,128,64//64,128,256
      - //0,512//512,256,256//-1
      - //0,512,256//256,128,256//-1
      - //0,512,256,128//128,128,128,128//128,256
      - //0,512//512,256,128//128,256
  pooling:
    value: SAGPooling
  dropout:
    value: 0
  
  # Training parameters
  optim_metric:
    value: MSE
  epochs:
    value: 300
  batch_size:
    values: [512,256,128,64]  
  shuffle:
    value: "true"
  lr:
    values: [1e-4,1e-05,1e-06]
  optimizer:
    value: Adam
  momentum:
    value: 0.9
  average_test:
    value: "false"
  cuda:
    value: "0"
  exp_name:
    value: None
  
  
  
  