program: main_STNet.py
method: bayes
metric:
  goal: minimize
  name: best_val_MSE

parameters:
  # Dataset parameters
  dataset:
    value: stnet_dataset
  cell_min_counts:
    value: 700
  cell_max_counts:
    value: 100000
  gene_min_counts:
    value: 1000
  gene_max_counts:
    value: 1000000
  min_exp_frac:
    value: 0.01
  min_glob_exp_frac:
    value: 0.60
  top_moran_genes:
    value: 256
  wildcard_genes:
    value: None
  combat_key:
    value: patient
  random_samples:
    value: -1
  plotting_slides:
    value: BC24105_D1,BC23277_D2,BC23270_E1,BC23508_D2
  plotting_genes:
    value: ENSG00000254709,ENSG00000184009,ENSG00000130726,ENSG00000241468
  patch_scale:
    value: 1.0
  patch_size:
    value: 224
  force_compute:
    value: "false"
  prediction_layer:
    value: c_d_log1p
  n_hops:
    value: 1

  # Model parameters
  sota:
    value: stnet
  img_backbone:
    value: densenet
  img_use_pretrained:
    value: "true"
  pretrained_ie_path:
    value:  None
  freeze_img_encoder:
    value: "false"
  act:
    value: None
  graph_operator:
    value: None
  pos_emb_sum:
    value: "false"
  h_global:
    value: "0//0//0"
  pooling:
    value: None
  dropout:
    value: 0.0

  # Training parameters
  optim_metric:
    value: MSE
  epochs:
    value: 50
  batch_size:
    values: [32,64,128,256,320]
    distribution: categorical
  shuffle:
    value: "true"
  lr:
    distribution: log_uniform_values
    max: 1e-2
    min: 1e-06
  optimizer:
    value: SGD
  momentum:
    value: 0.9
  average_test:
    value: "true"
  cuda:
    value: "0"
  exp_name:
    value: None